jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Compile with Gradle
      run: ./gradlew assembleAospOmega
    - continue-on-error: true
      id: set-result-artifact
      name: Save name of our Artifact
      run: 'ARTIFACT_PATHNAME_APK=$(ls build/outputs/apk/aospOmega/debug/*.apk | head
        -n 1)

        ARTIFACT_NAME_APK=$(basename $ARTIFACT_PATHNAME_APK)

        echo "ARTIFACT_NAME_APK is " ${ARTIFACT_NAME_APK}

        echo "ARTIFACT_PATHNAME_APK=${ARTIFACT_PATHNAME_APK}" >> $GITHUB_ENV

        echo "ARTIFACT_NAME_APK=${ARTIFACT_NAME_APK}" >> $GITHUB_ENV

        '
    - continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME_APK }}
        path: ${{ env.ARTIFACT_PATHNAME_APK }}
name: Neo Launcher CI
on:
  repository_dispatch:
    types: trigger-ga___android.yml
